### PR TITLE
Update ref-napi to 3.0.1

### PR DESCRIPTION
**Pull request by phwb**
Hi, update dependencies please

### CODE REVIEW

**Comment by Janealter** [comment]
What is the reason to update dependencies? This package already works on Node 12.

**Comment by phwb** [comment]
Hi!
When install `ref-napi` and `ref-wchar-napi` by `npm install`, it installs different version `ref-napi`, and it's broke runtime.

**Comment by Janealter** [comment]
Can you show your node_modules tree?

In fact, NPM implements a tree of dependencies in which two different versions of the same dependency can exist. I guess this is the case for binary packages as well.
[See this for info](https://lexi-lambda.github.io/blog/2016/08/24/understanding-the-npm-dependency-model/#dependency-duplication-and-the-dependency-tree)

I don't understand how two different versions of the same package conflict.

**Comment by phwb** [comment]
steps to reproduce:
- npm i ref-napi ref-wchar-napi
- npm ls ref-napi

and here is my tree
image

here is related comment
https://github.com/TooTallNate/ref-wchar/issues/2#issuecomment-195625055

**Comment by Janealter** [comment]
I see. Can you update only `ref-napi`? I don't see the reason to update other packages, especially with frozen versions.

**Comment by phwb** [comment]
> Can you update only ref-napi?

done

**Comment by Janealter** [comment]
Thanks for contributing!

**Pull request merged**
